import {Entity,PrimaryGeneratedColumn,Column,ManyToOne,Check, Unique,  CreateDateColumn, UpdateDateColumn} from "typeorm";
import {Users} from "./User";
@Entity()
@Check(`"amount" > 0`)
@Check(`"status" IN('SUCCESS','FAILED','PENDING')`)
@Unique([`gatewayTransactionId`])

  export class Transaction {
  @PrimaryGeneratedColumn()
  id: number;

 // @Column()
  //transactionId: string; // Unique transaction ID generated by the system                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          m      
  @Column()
  gatewayTransactionId: string;

  @Column({ name: "payee_vpa",nullable:true})
  payeeVpa: string;

  @Column({ name: "payer_vpa" ,nullable:true})
  payerVpa: string;

  @Column({ name: "payee_name",nullable:true })
  payeeName: string;

  @Column({ name: "payer_name",nullable:true })
  payerName: string;

  @Column()
  amount: number;

  @Column()
    status:string;

  @Column({nullable:true})
    gateway_transaction_code:string; 

 //@Column("jsonb",{nullable:true})
    meta: any;
 @Column({nullable:true})
 typeofcb : string 

 @CreateDateColumn({ type: "timestamp with time zone" })
    created_at: Date;
 @UpdateDateColumn({type: "timestamp with time zone"})
   updated_at:Date;

 @ManyToOne(()=> Users,(user)=> user.transactions)
    user:Users;
}
